name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get the latest commit info
      id: get_commit
      run: |
        echo "commit=$(git log -1 --format='%H')" >> $GITHUB_ENV
        echo "message=$(git log -1 --format='%s')" >> $GITHUB_ENV
        echo "author=$(git log -1 --format='%an')" >> $GITHUB_ENV

    - name: Update VERSION.txt
      run: |
        echo "Branch: ${{ github.ref_name }}" > VERSION.txt
        echo "Commit: ${{ env.commit }}" >> VERSION.txt
        echo "Author: ${{ env.author }}" >> VERSION.txt
        echo "Message: ${{ env.message }}" >> VERSION.txt

    - name: Upload files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        exclude: |
          .git*
          .github/*
          VERSION.txt

    - name: Upload VERSION.txt
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: VERSION.txt
        remote-dir: ./
